// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Curiosity is the predicate function for curiosity builders.
type Curiosity func(*sql.Selector)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserCuriosity is the predicate function for usercuriosity builders.
type UserCuriosity func(*sql.Selector)
