// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/danielmesquitta/api-pet-curiosities/internal/provider/db/ent/pet"
	"github.com/google/uuid"
)

// Pet is the model entity for the Pet schema.
type Pet struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Specie holds the value of the "specie" field.
	Specie pet.Specie `json:"specie,omitempty"`
	// Breed holds the value of the "breed" field.
	Breed string `json:"breed,omitempty"`
	// Search holds the value of the "search" field.
	Search string `json:"search,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PetQuery when eager-loading is set.
	Edges        PetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PetEdges holds the relations/edges for other nodes in the graph.
type PetEdges struct {
	// Curiosities holds the value of the curiosities edge.
	Curiosities []*Curiosity `json:"curiosities,omitempty"`
	// Owners holds the value of the owners edge.
	Owners []*User `json:"owners,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CuriositiesOrErr returns the Curiosities value or an error if the edge
// was not loaded in eager-loading.
func (e PetEdges) CuriositiesOrErr() ([]*Curiosity, error) {
	if e.loadedTypes[0] {
		return e.Curiosities, nil
	}
	return nil, &NotLoadedError{edge: "curiosities"}
}

// OwnersOrErr returns the Owners value or an error if the edge
// was not loaded in eager-loading.
func (e PetEdges) OwnersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Owners, nil
	}
	return nil, &NotLoadedError{edge: "owners"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pet.FieldSpecie, pet.FieldBreed, pet.FieldSearch:
			values[i] = new(sql.NullString)
		case pet.FieldCreatedAt, pet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case pet.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pet fields.
func (pe *Pet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pet.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pe.ID = *value
			}
		case pet.FieldSpecie:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field specie", values[i])
			} else if value.Valid {
				pe.Specie = pet.Specie(value.String)
			}
		case pet.FieldBreed:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field breed", values[i])
			} else if value.Valid {
				pe.Breed = value.String
			}
		case pet.FieldSearch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field search", values[i])
			} else if value.Valid {
				pe.Search = value.String
			}
		case pet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				pe.CreatedAt = value.Time
			}
		case pet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				pe.UpdatedAt = value.Time
			}
		default:
			pe.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pet.
// This includes values selected through modifiers, order, etc.
func (pe *Pet) Value(name string) (ent.Value, error) {
	return pe.selectValues.Get(name)
}

// QueryCuriosities queries the "curiosities" edge of the Pet entity.
func (pe *Pet) QueryCuriosities() *CuriosityQuery {
	return NewPetClient(pe.config).QueryCuriosities(pe)
}

// QueryOwners queries the "owners" edge of the Pet entity.
func (pe *Pet) QueryOwners() *UserQuery {
	return NewPetClient(pe.config).QueryOwners(pe)
}

// Update returns a builder for updating this Pet.
// Note that you need to call Pet.Unwrap() before calling this method if this Pet
// was returned from a transaction, and the transaction was committed or rolled back.
func (pe *Pet) Update() *PetUpdateOne {
	return NewPetClient(pe.config).UpdateOne(pe)
}

// Unwrap unwraps the Pet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pe *Pet) Unwrap() *Pet {
	_tx, ok := pe.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pet is not a transactional entity")
	}
	pe.config.driver = _tx.drv
	return pe
}

// String implements the fmt.Stringer.
func (pe *Pet) String() string {
	var builder strings.Builder
	builder.WriteString("Pet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pe.ID))
	builder.WriteString("specie=")
	builder.WriteString(fmt.Sprintf("%v", pe.Specie))
	builder.WriteString(", ")
	builder.WriteString("breed=")
	builder.WriteString(pe.Breed)
	builder.WriteString(", ")
	builder.WriteString("search=")
	builder.WriteString(pe.Search)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(pe.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(pe.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Pets is a parsable slice of Pet.
type Pets []*Pet
