// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/danielmesquitta/api-pet-curiosities/internal/provider/db/ent/curiosity"
	"github.com/danielmesquitta/api-pet-curiosities/internal/provider/db/ent/user"
	"github.com/danielmesquitta/api-pet-curiosities/internal/provider/db/ent/usercuriosity"
	"github.com/google/uuid"
)

// UserCuriosity is the model entity for the UserCuriosity schema.
type UserCuriosity struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Viewed holds the value of the "viewed" field.
	Viewed bool `json:"viewed,omitempty"`
	// Liked holds the value of the "liked" field.
	Liked bool `json:"liked,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserCuriosityQuery when eager-loading is set.
	Edges        UserCuriosityEdges `json:"edges"`
	user_id      *uuid.UUID
	curiosity_id *uuid.UUID
	selectValues sql.SelectValues
}

// UserCuriosityEdges holds the relations/edges for other nodes in the graph.
type UserCuriosityEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Curiosity holds the value of the curiosity edge.
	Curiosity *Curiosity `json:"curiosity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCuriosityEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CuriosityOrErr returns the Curiosity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCuriosityEdges) CuriosityOrErr() (*Curiosity, error) {
	if e.Curiosity != nil {
		return e.Curiosity, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: curiosity.Label}
	}
	return nil, &NotLoadedError{edge: "curiosity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCuriosity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercuriosity.FieldViewed, usercuriosity.FieldLiked:
			values[i] = new(sql.NullBool)
		case usercuriosity.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case usercuriosity.FieldID:
			values[i] = new(uuid.UUID)
		case usercuriosity.ForeignKeys[0]: // user_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case usercuriosity.ForeignKeys[1]: // curiosity_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCuriosity fields.
func (uc *UserCuriosity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercuriosity.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				uc.ID = *value
			}
		case usercuriosity.FieldViewed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field viewed", values[i])
			} else if value.Valid {
				uc.Viewed = value.Bool
			}
		case usercuriosity.FieldLiked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field liked", values[i])
			} else if value.Valid {
				uc.Liked = value.Bool
			}
		case usercuriosity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				uc.CreatedAt = value.Time
			}
		case usercuriosity.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				uc.user_id = new(uuid.UUID)
				*uc.user_id = *value.S.(*uuid.UUID)
			}
		case usercuriosity.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field curiosity_id", values[i])
			} else if value.Valid {
				uc.curiosity_id = new(uuid.UUID)
				*uc.curiosity_id = *value.S.(*uuid.UUID)
			}
		default:
			uc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCuriosity.
// This includes values selected through modifiers, order, etc.
func (uc *UserCuriosity) Value(name string) (ent.Value, error) {
	return uc.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserCuriosity entity.
func (uc *UserCuriosity) QueryUser() *UserQuery {
	return NewUserCuriosityClient(uc.config).QueryUser(uc)
}

// QueryCuriosity queries the "curiosity" edge of the UserCuriosity entity.
func (uc *UserCuriosity) QueryCuriosity() *CuriosityQuery {
	return NewUserCuriosityClient(uc.config).QueryCuriosity(uc)
}

// Update returns a builder for updating this UserCuriosity.
// Note that you need to call UserCuriosity.Unwrap() before calling this method if this UserCuriosity
// was returned from a transaction, and the transaction was committed or rolled back.
func (uc *UserCuriosity) Update() *UserCuriosityUpdateOne {
	return NewUserCuriosityClient(uc.config).UpdateOne(uc)
}

// Unwrap unwraps the UserCuriosity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (uc *UserCuriosity) Unwrap() *UserCuriosity {
	_tx, ok := uc.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCuriosity is not a transactional entity")
	}
	uc.config.driver = _tx.drv
	return uc
}

// String implements the fmt.Stringer.
func (uc *UserCuriosity) String() string {
	var builder strings.Builder
	builder.WriteString("UserCuriosity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", uc.ID))
	builder.WriteString("viewed=")
	builder.WriteString(fmt.Sprintf("%v", uc.Viewed))
	builder.WriteString(", ")
	builder.WriteString("liked=")
	builder.WriteString(fmt.Sprintf("%v", uc.Liked))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(uc.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserCuriosities is a parsable slice of UserCuriosity.
type UserCuriosities []*UserCuriosity
