// Code generated by ent, DO NOT EDIT.

package usercuriosity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/danielmesquitta/api-pet-curiosities/internal/provider/db/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldLTE(FieldID, id))
}

// Viewed applies equality check predicate on the "viewed" field. It's identical to ViewedEQ.
func Viewed(v bool) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldEQ(FieldViewed, v))
}

// Liked applies equality check predicate on the "liked" field. It's identical to LikedEQ.
func Liked(v bool) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldEQ(FieldLiked, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldEQ(FieldCreatedAt, v))
}

// ViewedEQ applies the EQ predicate on the "viewed" field.
func ViewedEQ(v bool) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldEQ(FieldViewed, v))
}

// ViewedNEQ applies the NEQ predicate on the "viewed" field.
func ViewedNEQ(v bool) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldNEQ(FieldViewed, v))
}

// LikedEQ applies the EQ predicate on the "liked" field.
func LikedEQ(v bool) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldEQ(FieldLiked, v))
}

// LikedNEQ applies the NEQ predicate on the "liked" field.
func LikedNEQ(v bool) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldNEQ(FieldLiked, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserCuriosity {
	return predicate.UserCuriosity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserCuriosity {
	return predicate.UserCuriosity(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCuriosity applies the HasEdge predicate on the "curiosity" edge.
func HasCuriosity() predicate.UserCuriosity {
	return predicate.UserCuriosity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CuriosityTable, CuriosityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCuriosityWith applies the HasEdge predicate on the "curiosity" edge with a given conditions (other predicates).
func HasCuriosityWith(preds ...predicate.Curiosity) predicate.UserCuriosity {
	return predicate.UserCuriosity(func(s *sql.Selector) {
		step := newCuriosityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserCuriosity) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserCuriosity) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserCuriosity) predicate.UserCuriosity {
	return predicate.UserCuriosity(sql.NotPredicates(p))
}
